version: '3'

services:
  powerbot:
    restart: always
    container_name: powerbot
    environment:
      ROON_BASE_URL: "http://thmbp:3001"
    env_file: [config/docker.env]
    image: powerbot:latest
    ports: ["8810:8810"]
