version: '3'

services:
  powerbot:
    restart: always
    container_name: powerbot
    env_file: [ config/docker.env ]
    # image: powerbot:latest
    build:
      context: .
      args:
        APP_NAME: powerbot
        APP_VSN: 0.0.1
    ports: [ "8810:8810" ]
