use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :powerbot, PowerbotWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :powerbot, PowerbotWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/powerbot_web/views/.*(ex)$},
      ~r{lib/powerbot_web/templates/.*(eex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

config :powerbot, :sparky,
  host: "sparky.threadbox.net",
  delay_shutdown: 8

config :powerbot, :p12, host: "p12.threadbox.net"

config :powerbot, :roon,
  base_url: "http://localhost:3001",
  find_zone_delay: 10,
  zones: [
    dave: [
      "1601f06ee3ecdab4007f17fc1f92c20112ff",
      "160105d2151b25b726cf541876d70bff6c23"
    ],
    autechre: ["1601cada42df00f0879bd9619519205719f4"]
  ]
  # zones: [:dave, :da_dave],
  # zone_map: %{
  #   dave: "1601f06ee3ecdab4007f17fc1f92c20112ff",
  #   da_dave: "160105d2151b25b726cf541876d70bff6c23"
  # }

# Powerbot instance, running on my NAS. This one is important because it is
# ablse to reach the p12 (PS Audio Power Plant) to issue it commands
config :powerbot, :nas_powerbot,
  base_url: "http://bookshelf.threadbox.net:4000"
